version: 0.2

phases:
  install:
    commands: 
      - cd frontend/devops-practice-app
      - aws codeartifact login --tool npm --repository resume-devops-repo --domain resume --domain-owner 242201278004 --region us-east-2
      - npm install
      
  pre_build:
    commands:
      - echo "Installing dependecies... "
    
  build:
    commands:
      - echo Build started on `date`
      - npm run build
  post_build:
    commands:
      - echo Build completed on `date`

artifacts:
  files:
    - '**/*'
  base-directory: build